version: "3.0"

services:
  api:
    container_name: "icer-api"
    volumes:
      - ./app:/app
    build: .
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${HOST_NAME}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${HOST_NAME}
      - LETSENCRYPT_EMAIL=${DEMAIL}
networks:
  default:
    external: true
    name: nginx-proxy
